services:
  ollama:
    image: ollama/ollama
    container_name: ollama
    entrypoint: /entrypoint.sh
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    ports:
      - 11434:11434
    volumes:
      # - ollama-data::/root/.ollama
      - ./ollama-data:/root/.ollama
      - ./entrypoint.sh:/entrypoint.sh
    networks:
      - ollama-docker

networks:
  ollama-docker:
    driver: bridge

# volumes:
#   ollama:
#     # driver: local
#     external: true